export const GET_ALL_LATEST_RATE = 'GET_ALL_LATEST_RATE';
export const GET_ALL_LATEST_RATE_SUCCESS = 'GET_ALL_LATEST_RATE_SUCCESS';
export const GET_ALL_LATEST_RATE_FAIL = 'GET_ALL_LATEST_RATE_FAIL';
export const CHANGE_INITIAL_VALUE = 'CHANGE_INITIAL_VALUE';
export const SUBMIT_RATES_VALUE = 'SUBMIT_RATES_VALUE';
export const REMOVE_RATES_VALUE = 'REMOVE_RATES_VALUE';